#!/usr/bin/env python

import sys

from scanning_gui.scanning import ScanningPlugin
from rqt_gui.main import Main

plugin = 'scanning_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
