#!/usr/bin/env python

import sys

from sl_sensor_scanning_gui.sl_sensor_scanning import SLSensorScanningPlugin
from rqt_gui.main import Main

plugin = 'sl_sensor_scanning_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
