#!/usr/bin/env python

import sys

from sl_sensor_calibration_gui.sl_sensor_calibration import SLSensorCalibrationPlugin
from rqt_gui.main import Main

plugin = 'sl_sensor_calibration_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
